In [9]:
import pandas as pd 
import numpy as np

In [2]:
pd.__version__

'2.3.3'

In [3]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [7]:
lst = [1,2,3,4,5]
df = pd.DataFrame(lst, columns=['a'])
df

   a
0  1
1  2
2  3
3  4
4  5

In [11]:
data = { 'A': np.array([1, 4, 7]),
         'B': np.array([2, 5, 8]),
         'C': np.array([3, 6, 9]) }

df = pd.DataFrame(data)
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [15]:
# List of dictionaries
data = [
    {'name': 'Mike', 'degree': 'MBA', 'score': 90},
    {'name': 'Dan', 'degree': 'BCA', 'score': 40},
    {'name': 'Emilia', 'degree': 'M.Tech', 'score': 80},
]
df = pd.DataFrame(data)
print(df)

df = pd.json_normalize(data)
print(df)

     name  degree  score
0    Mike     MBA     90
1     Dan     BCA     40
2  Emilia  M.Tech     80
     name  degree  score
0    Mike     MBA     90
1     Dan     BCA     40
2  Emilia  M.Tech     80

In [17]:
data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns=['names','id'])
print(df)

  names  id
0   tom  10
1  nick  15
2  juli  14

In [19]:
data = [{'b': 2, 'c': 3}, {'a': 10, 'b': 20, 'c': 30}]
df = pd.DataFrame(data)
print(df)

    b   c     a
0   2   3   NaN
1  20  30  10.0

In [20]:
data = [{'b': 2, 'c': 3}, {'a': 10, 'b': 20, 'c': 30}]
df = pd.DataFrame(data)
print(df.index)

RangeIndex(start=0, stop=2, step=1)

In [21]:
data = { 'A': np.array([1, 4, 7]),
         'B': np.array([2, 5, 8]),
         'C': np.array([3, 6, 9]) }

df = pd.DataFrame(data)
df.set_index('A')

   B  C
A
1  2  3
4  5  6
7  8  9

In [26]:
df.reset_index(drop=True)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [30]:
data = {'age': [25, 30], 'city': ['NY', 'LA']}
df = pd.DataFrame(data, index=['Alice', 'Bob'])

df.loc['Alice']

age     25
city    NY
Name: Alice, dtype: object

In [32]:
data = {'age': [25, 30,40,50,60], 'city': ['NY', 'LA','aa','bb','cc']}
df = pd.DataFrame(data)

df.loc[0:2]

   age city
0   25   NY
1   30   LA
2   40   aa

In [35]:
df.iloc[0]

age     25
city    NY
Name: 0, dtype: object

In [36]:
data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'], 
        'Age': [25, 30, 22, 35, 28], 
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'], 
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
# Display the entire DataFrame
print(df)

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [37]:
print(df['Age'])

0    25
1    30
2    22
3    35
4    28
Name: Age, dtype: int64

In [44]:

print(df.iloc[1], ['Name','age'])

Name       Alice
Age           30
Gender    Female
Salary     55000
Name: 1, dtype: object ['Name', 'age']

In [46]:
print(df[df['Age'] > 30])

  Name  Age  Gender  Salary
3  Eve   35  Female   70000

In [49]:
salary_at_index_2 = df.at[2, 'Salary']
print(salary_at_index_2)

40000

In [53]:
data = pd.read_csv("convertcsv.csv")
data

,seq,name/first,name/last,age,street,city,state,zip,dollar,pick,date
0,1,Annie,West,56,Ewni Road,Habmufa,WY,4615,$771.59,YELLOW,11/27/2061
1,2,Bruce,Curtis,54,Avvu Highway,Ileripuje,NH,8824,$3905.25,WHITE,06/18/2008
2,3,Micheal,Guzman,54,Megon Avenue,Tonihi,WI,3686,$626.97,GREEN,10/21/2012
3,4,Claudia,Baldwin,30,Ozawo Key,Katsepev,HI,61704,$9185.22,WHITE,02/19/1924
4,5,Ora,Greer,64,Goca Point,Gugofso,PA,5022,$680.58,BLUE,10/17/1951
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Adeline,Burgess,20,Ruga Turnpike,Hakkazi,VA,55866,$1067.25,GREEN,02/18/2031
96,97,Ollie,Cain,59,Dimgi Street,Olipaimo,NJ,94970,$7267.36,GREEN,09/01/1943
97,98,Tommy,Wong,54,Zuwac Extension,Ciwece,DE,73731,$2943.08,YELLOW,10/13/1970
98,99,Antonio,Powers,53,Mesgal Parkway,Fugojifom,WA,42526,$2461.29,BLUE,06/13/1928
99,100,Estella,Wilkins,21,Akpiv Glen,Sidewag,NJ,97023,$8077.25,WHITE,02/20/2038

In [54]:
print(data.head(5))
print(data.tail(5))

   seq name/first name/last  age        street       city state    zip  \
0    1      Annie      West   56     Ewni Road    Habmufa    WY   4615
1    2      Bruce    Curtis   54  Avvu Highway  Ileripuje    NH   8824
2    3    Micheal    Guzman   54  Megon Avenue     Tonihi    WI   3686
3    4    Claudia   Baldwin   30     Ozawo Key   Katsepev    HI  61704
4    5        Ora     Greer   64    Goca Point    Gugofso    PA   5022

     dollar    pick        date
0   $771.59  YELLOW  11/27/2061
1  $3905.25   WHITE  06/18/2008
2   $626.97   GREEN  10/21/2012
3  $9185.22   WHITE  02/19/1924
4   $680.58    BLUE  10/17/1951
    seq name/first name/last  age           street       city state    zip  \
95   96    Adeline   Burgess   20    Ruga Turnpike    Hakkazi    VA  55866
96   97      Ollie      Cain   59     Dimgi Street   Olipaimo    NJ  94970
97   98      Tommy      Wong   54  Zuwac Extension     Ciwece    DE  73731
98   99    Antonio    Powers   53   Mesgal Parkway  Fugojifom    WA  42526
99  100    Estella   Wilkins   21       Akpiv Glen    Sidewag    NJ  97023

      dollar    pick        date
95  $1067.25   GREEN  02/18/2031
96  $7267.36   GREEN  09/01/1943
97  $2943.08  YELLOW  10/13/1970
98  $2461.29    BLUE  06/13/1928
99  $8077.25   WHITE  02/20/2038

In [55]:
data.columns

Index(['seq', 'name/first', 'name/last', 'age', 'street', 'city', 'state',
       'zip', 'dollar', 'pick', 'date'],
      dtype='object')

In [56]:
# MULTIPLE COLUMNS SELECTED 
selected_col = data[['name/first','name/last','age']]
print(selected_col.head(5))

  name/first name/last  age
0      Annie      West   56
1      Bruce    Curtis   54
2    Micheal    Guzman   54
3    Claudia   Baldwin   30
4        Ora     Greer   64

In [63]:
data = data.set_index(data['name/first'])

In [64]:
print(data.loc['Annie'])

            seq name/first name/last  age      street     city state    zip  \
name/first
Annie         1      Annie      West   56   Ewni Road  Habmufa    WY   4615
Annie        66      Annie     Mason   35  Obob Place  Gauhele    AZ  63453

              dollar    pick        date
name/first
Annie        $771.59  YELLOW  11/27/2061
Annie       $7550.37     RED  09/08/2001

In [66]:
# Select all rows and specific columns 

print(data[['seq', 'street']])

            seq           street
name/first
Annie         1        Ewni Road
Bruce         2     Avvu Highway
Micheal       3     Megon Avenue
Claudia       4        Ozawo Key
Ora           5       Goca Point
...         ...              ...
Adeline      96    Ruga Turnpike
Ollie        97     Dimgi Street
Tommy        98  Zuwac Extension
Antonio      99   Mesgal Parkway
Estella     100       Akpiv Glen

[100 rows x 2 columns]

In [68]:
selection = data.iloc[[3, 4], [1, 2]]
print(selection)

           name/first name/last
name/first
Claudia       Claudia   Baldwin
Ora               Ora     Greer

In [69]:
selection = data.iloc[:, [1, 2]]
print(selection)

           name/first name/last
name/first
Annie           Annie      West
Bruce           Bruce    Curtis
Micheal       Micheal    Guzman
Claudia       Claudia   Baldwin
Ora               Ora     Greer
...               ...       ...
Adeline       Adeline   Burgess
Ollie           Ollie      Cain
Tommy           Tommy      Wong
Antonio       Antonio    Powers
Estella       Estella   Wilkins

[100 rows x 2 columns]

In [70]:
player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
print(df)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

In [71]:
df1 = df.iloc[0:4]
print(df1)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000

In [72]:
df1 = df.iloc[:,1:2]
print(df1)

   Age
0   36
1   38
2   31
3   34
4   40
5   33
6   42

In [77]:
# selecting a specific cell
# selecting a specific cell
print(player_list[2][3])

8428000

In [78]:
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],
                          
                          'Age': [30, 35, 37, 33, 34, 30],
                          
                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],
                          
                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

# display dataframe
display(dataFrame)

         Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
1    MONICA     35   93000         CHEF
2    PHOEBE     37   88000        MASUS
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST

In [81]:
display(dataFrame[dataFrame['Age']>33], ['Name','Age'])

        Name  Age  Salary    JOB
1   MONICA     35   93000   CHEF
2   PHOEBE     37   88000  MASUS
4   CHANDLER   34   94000     IT

['Name', 'Age']